### PR TITLE
Revert "Introduce an HTTP server for unit tests. Redesign webdriver harness t…"

### PR DESCRIPTION
**Pull request by krunal3103**
Reverts krunal3103/servo#1
I can merge this request once my professor reviews my code and grades this assignment. I hope this is fine

### CODE REVIEW

**Comment by jdm** [comment]
Um, not exactly. I proposed these changes because I think they're important infrastructure for the rest of the code your group will be writing for the project. I wrote them as a pull request because I didn't know precisely how to accomplish my ideas until I had tried them out, and then describing precisely the solution I had in mind would be a distraction from the more important work in the rest of the project.

**Comment by krunal3103** [comment]
okay. so this was just a guideline for subsequent work?
Alright. I have reverted back the pull request and i`ll check out the code and think in this track forward

**Comment by jdm** [comment]
Right, this isn't something I described in the original project, it's just something I realized was necessary when I looked at the first tests that your group put together.

**Comment by krunal3103** [comment]
Hey Josh,
We are trying to integrate the HTTP server for unit tests. Also for the
subsequent steps mentioned for the project, we are kind of confused as we
don`t have much idea how servo works.
Could you in brief explain us that what exactly are we required to do for
the different tests as whatever is described is too ambiguous! A little
headstart would be highly appreciated.

class TestStringMethods(unittest.TestCase):
    def test_get(self):
        with ServoProcess():
            session = webdriver.Session('127.0.0.1', 7000)
            session.start()
            session.url = "http://google.com/about"
            self.assertEqual(session.url, "https://www.google.com/about/")
            session.end()

```
def test_u(self):
print "test"
with ServoProcess():
session = webdriver.Session('127.0.0.1', 7000)
   session.start()
   session.send_command("GET", session.url)
   # resp = a._connection.getresponse()
   # self.assertEqual(resp.status, "200")
   # print resp
```

We were trying something of this sort for the lower level API commands but
couldn`t access status code and print the error message.
Thanks

Regards,
Krunal Gala

**Comment by jdm** [comment]
Ok, so to make sure we're all on the same page here:
- there is the [specification](https://w3c.github.io/webdriver/webdriver-spec.html) which defines a way of communicating with and controlling a user agent that exposes a server that supports the webdriver protocol
- Servo implements this server in the [webdriver_server](https://github.com/servo/servo/blob/master/components/webdriver_server/lib.rs) crate (and associated support files like [webdriver_msg.rs](https://github.com/servo/servo/blob/master/components/msg/webdriver_msg.rs) and [webdriver_handlers.rs](http://mxr.mozilla.org/servo/source/components/script/webdriver_handlers.rs)
- however, this implementation has no automated testing verifying that its behaviour matches the text of the specification

So, the goal of this project is to write a bunch of tests that verify properties of the specification. For example, step 4 of https://w3c.github.io/webdriver/webdriver-spec.html#get says that a specific error code should be returned if the POST body does not contain a field named "url", which would be one useful testcase.

As for interacting with the webdriver session, note that the `send_command` method takes several arguments:
- an HTTP method (eg. "POST", "GET", etc.)
- a webdriver server endpoint (such as "url", which would then be turned into `session/{session_id}/url`) which corresponds to the "path template" referred to in the specification
- a request body (such as `{ url: "http://google.com" }`)

Take a look at how the higher-level APIs such as session.url are implemented on top of send_command in the definition of the Session class in [webdriver.py](https://github.com/servo/servo/blob/84ab7e9fe8f4a6528995eff3eb6e814cb724c364/tests/wpt/harness/wptrunner/executors/webdriver.py#L426) for a useful model. The result of calling `send_command` should yield objects or exceptions that allow introspection into the operation that was just performed.

Does that help?

**Comment by jdm** [comment]
Oh, and as for how the HTTP server fits into things here, it's required in order to control the data that Servo ends up receiving as a result of executing webdriver commands. For example, one of the requested testcases is "Try Get with pages that return non-200 responses." - this means that the HTTP server should return HTTP responses like 302, or 500, or 404, and the tests should verify that the expected behaviour for the webdriver client occurs (from my reading of https://w3c.github.io/webdriver/webdriver-spec.html#get, it looks like it should still receive a "success" value from step 8).

**Pull request merged**
